---
- name: packages | install
  apt: >
    pkg={{item}}
    state=installed
    update-cache=yes
  with_items:
    - r-base
    - r-base-dev
    - gdebi-core
    - unixodbc-dev
    - openjdk-8-jdk
    - libmysqlclient-dev
    - libgdal-dev
    - libproj-dev

