---
- include: repository.yml
  tags:
    - configuration
    - r
    - r-repository

- name: Install Packages
  apt: >
    pkg={{item}}
    state=installed
    update-cache=yes
  with_items:
    - r-base
    - r-base-dev
    # For Shiny
    - gdebi-core
    # For RODBC
    - libiodbc2
    - libiodbc2-dev
  tags:
    - r

- include: packages.yml
  tags:
    - configuration
    - r
    - r-packages
