---
- name: packages | install
  apt: >
    pkg={{item}}
    state=installed
    update-cache=yes
  with_items:
    - ufw
    - htop
    - tmux
    - packaging-dev
    - build-dep
    - libcurl4-gnutls-dev
    - libcurl4-gnutls-dev
    - libxml2-dev
