---
- name: Download Shiny deb via wget
  command: /usr/bin/wget "{{ shiny_deb }}" -O shiny.deb && /usr/bin/gdebi ~/shiny.deb --n
  args:
    chdir: "~"
    creates: ~/shiny.deb
  register: get_shiny

